// An "account". Every object in here will be stored locally.
class User
{
    // Multiple shipping addresses possible.
    shippingInfo = [];

    // Multiple payment methods possible.
    paymentMethods = [];

    // Cart with items.
    cart = null;

    // Set up the user!!!
    constructor() 
    {
        // It's fine if these are null, it just means that there's no info for them yet
        // Get the keys for the shipping info, and payment methods
        this.shippingInfo = window.localStorage.getItem( "shippinginfo" );
        this.paymentMethods = window.localStorage.getItem( "paymentmethods" );

        // Find a cart, if not then make a new cart.
        this.cart = window.localStorage.getItem( "cart" );
        if ( this.cart )
        {
            cart = new Cart();

            // Save this.
            window.localStorage.setItem( cart, "cart" );
        }

        console.log( this );
    }

    // items in the wishlist to display to the user. Show to user in /wishlists.html
    Wishlist = [];
}

// Store these if the user wants it to be stored
// Shipping Info to store.
class ShippingInfo 
{
    // Generated by the webpage.
    constructor( fname, lname, aLine1, aLine2, _city, _area, _pNumber, _ZIP, _Country )
    {
        this.firstName = fname;
        this.lname = lastName;
        this.addressLine1 = aLine1;
        this.addressLine2 = aLine2;
        this.city = _city;
        this.area = _area;
        this.phoneNumber = _pNumber;
        this.ZIP = _ZIP;
        this.Country = _Country;
    }

    // Name for shipping.
    firstName = "";
    lastName = "";
    // Address 
    addressLine1 = "";
    // Apartment, suite, etc
    addressLine2 = "";
    // City 
    city = "";
    // State/Province/Region
    area = "";
    // Phone number
    phoneNumber = "";
    // ZIP or Postal Code
    ZIP = "";

    // Country
    //Country = "";
}

// Credit/Debit Card Info.
class PaymentInfo 
{
    // Constructor. Generated by the webpage
    constructor( _name, _cardNumber, _securityCode, _expireCode, _shippingInfo )
    {
        this.name = _name;
        this.cardNumber = _cardNumber;
        this.securityCode = _securityCode;
        this.expireCode = _expireCode;
        this.shippingInfo = _shippingInfo;
    }

    // Cardholder Name
    name = "";
    // Card Number
    cardNumber = "";
    // CVC in back of card
    securityCode = "";
    // Expiration Date for card
    expireDate = new Date( "1-1-2100" );
    // Billing address. (ShippingInfo object)
    billingAddress = null;
}